action_type: ta without height change
agents_per_gpu: 1
anchor_point:
- 8.18362
- 47.6014
area_measurable_per_step: 72713.151
batch_size: 256
buffer_size: 1600000
clip_range: 0.3
commit_id: 8c9b1e22a49a0bc284d353daf313058919647f23
constant_radiation_reward: -10
cpus_per_task: 16
create_lookup_files: true
distance_east_from_anchor_point: 10000
distance_north_from_anchor_point: 10000
ent_coef: 0.8
env_id: GymnasiumEnv-v18
episode_length_factor: 1.3
file_name_to_run_via_cluster: train_model_with_multiple_agents.py
gamma: 0.9995
gradient_steps_sac: 1
gradient_steps_td3: 1
granularity: 150
how_to_calculate_odl: via simulated radiation grid
include_action_noise: true
include_direction_z_achsis_in_observation: false
include_distance_to_points: false
include_reward_for_little_action_with_weight_but_added_instead_of_multiplied: true
largest_horizontal_turning_angle_deg: 90
largest_vertical_height_change_per_second: 5
learning_rate: 0.0001
learning_rate_sac: 1.0e-05
learning_rate_td3: 1.0e-05
learning_starts: 10000
limit_percentage_for_remeasured_area_before_termination: 0.05
logging_frequency: 50000
max_amount_of_timesteps: 2
max_desired_coverage_percent: 97
max_distance: 500
max_grid_height: 1000
max_incremental_tv: 1
measured_area_heatmap_granularity: 4
middle_of_episode_percentage_of_measured_area_static_or_dynamic: dynamic
min_desired_coverage_percent: 10
n_epochs: 6
n_eval_episodes: 100
n_steps: 256
name_of_geocoordinates_array: programmatically_loaded_heightmap_geocoordinates
name_of_heightmap: programmatically_loaded_heightmap
no_measurement_cone_calc: true
no_observed_radiation_scale_0_1: 0.3
num_envs_for_training: 16
num_scenarios: 20
observed_image_size: 51
observed_radiation_grid_creation_type: colored via position
only_one_distorted_image_in_observation: true
policy_type: MultiInputPolicy
radiation_data_shapefile_name: Total_gamma_dose_rate.shp
radiation_value_to_avoid: 25
rew_weight_height_interpolation: 0.1
reward_for_little_action_weight_of_summand: 0.8
reward_for_time_passed: 0.0
sb3_model_type: TD3
sigma_coef_for_noise: 0.2
speed_in_meters_per_second: 33.333333
start_time: 1656316000.0
surface_grid_creation_type: no_height_map
sweep_info: ' 100000 scenarios'
time_for_each_agent: 5-22:59:00
timestep: 4.5
total_timesteps_for_training: 10000000000
train_freq_sac: 2
train_freq_td3: 2
training_library: sb3
weight_incremental_tv_reward: 0.0011
weight_percentage_of_new_measured_points: 2.4
